field.field_settings.simple_paypal_field:
  type: mapping
  label: 'Paid settings'
  mapping:
    amount:
      type: float
      label: 'Amount'
    on_label:
      type: string
      label: 'Label for checkboxes'
field.value.simple_paypal_field:
  type: mapping
  mapping:
    value:
      type: integer
      label: 'Value'
field.formatter.settings.paypal_smart_buttons:
  type: mapping
  label: 'PayPal Smart Buttons formatter settings'
  mapping:
    button_settings:
      type: sequence
      label: 'PayPal button settings'
      nullable: true
      sequence:
        type: string
        label: 'Setting'

field.widget.settings.paypal_smart_buttons:
  type: mapping
  label: 'Simple PayPal field widget settings'
  mapping:
    layout:
      type: string
      label: 'Buttons layouts'
    color:
      type: string
      label: 'Buttons color'
    shape:
      type: string
      label: 'Buttons shape'
    label:
      type: string
      label: 'Type of label'
    tagline:
      type: boolean
      label: 'Show tagline'
